aws_region        = "ap-south-1"                # Your AWS Region
project_name      = "YOUR_DATABASE_NAME"        # Name for your RDS instance
db_engine         = "mysql"                     # "mysql" or "postgres"
db_engine_version = "8.0"                       # MySQL 8.0 or PostgreSQL 15
db_instance_class = "db.t3.micro"               # Free tier eligible size
db_storage        = 20                          # Disk space in GB
db_name           = "YOUR_DB_SCHEMA_NAME"       # Default database/schema name (e.g., myapp)
db_username       = "YOUR_ADMIN_USERNAME"       # Master username (e.g., admin)
db_password       = "YOUR_STRONG_PASSWORD"      # ⚠️ Database password!
